services:
  web:
    build:
      context: .
      dockerfile: infra/docker/django/Dockerfile.prod
    container_name: django_app
    env_file:
      - .env.prod
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./infra/docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always
    profiles: ["production"]

volumes:
  static_volume: